GET http://localhost:3001/api/users/

###

POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "testUserName",
    "name": "Test Name",
    "password": "superSecret"
}

###

POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "testUserName2",
    "name": "Test Name2",
    "password": "superSecret2"
}


###

DELETE  http://localhost:3001/api/users/639c3e3fa7a8a94225334979 HTTP/1.1
content-type: application/json